"""initial

Revision ID: 121b9da97252
Revises:
Create Date: 2025-06-26 13:59:26.874223

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '121b9da97252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('_User__password', sa.String(length=128),
                      nullable=False, server_default='default_password')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_User__password')
    # ### end Alembic commands ###
